version: '2'
services:
  web:
    build: .
    command: npm start
    ports:
      - "2368:2368"
    volumes:
      - ./config.js:/var/www/ghost/config.js
      - ./backups-db:/var/www/ghost/backups-db
      - ./content:/var/www/ghost/content